apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow-sa
  namespace: pure-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role
  namespace: pure-agent
rules:
  - apiGroups: [""]
    resources: [pods, pods/log]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, create, delete]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [create, get, delete]
  - apiGroups: [argoproj.io]
    resources: [workflowtaskresults]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-binding
  namespace: pure-agent
subjects:
  - kind: ServiceAccount
    name: argo-workflow-sa
    namespace: pure-agent
roleRef:
  kind: Role
  name: argo-workflow-role
  apiGroup: rbac.authorization.k8s.io
